CREATE TABLE User4(
  userObjectId INTEGER AUTO_INCREMENT,
  id INTEGER,
  DateDays SMALLINT,
  DateMonths SMALLINT,
  DateYears SMALLINT,
  TimeSeconds SMALLINT,
  TimeMinutes SMALLINT,
  TimeHours SMALLINT,
  Type CHAR(20),
  Name CHAR(20),
  Description CHAR(128),
  Label INTEGER,
  Apperance INTEGER,
  Latitude FLOAT(9),
  Longitude FLOAT(9),
  Elevation INTEGER,
  RangeLethal INTEGER,
  RangeDetection INTEGER,
  Attachment CHAR(15),
  Speed FLOAT,
  Course INTEGER,
  WarningSensitive BOOL,
  Class INTEGER default 0,
  Source INTEGER default 0,
# shorter index name for Targa DTU
  KEY oi (userObjectId),
  KEY id (id),
  KEY ln (Longitude)
);
