#  EuroAvionics Macro - Recorded: 2022-06-03 11:50

UserInterface("","root").pressButton("BUTTON_MAP");
Menu("","MapMenu").setFocusedItem("itemDTEDProfile");
Menu("","MapMenu").setFocusedItem("itemMapLine");
Menu("","MapMenu").setFocusedItem("item_menuLabels");
MenuSubmenuItem("MapMenu","item_menuLabels").pressItem("0");
Menu("MapMenu","menuLabels").setFocusedItem("itemLabelsNormal");
Menu("MapMenu","menuLabels").setFocusedItem("itemLabelsOptimized");
MenuRadioItem("menuLabels","itemLabelsOptimized").select("0");
Menu("MapMenu","menuLabels").hideMenu("0");
Menu("","MapMenu").hideMenu("0");
