#  EuroAvionics Macro - Recorded: 2022-11-22 13:12

UserInterface("","root").pressButton("BUTTON_MENU");
Menu("","MainMenu").setFocusedItem("item_menuFlightPlan");
Menu("","MainMenu").setFocusedItem("itemFlightInfo");
Menu("","MainMenu").setFocusedItem("itemChecklists");
Menu("","MainMenu").setFocusedItem("itemIoStatus");
Menu("","MainMenu").setFocusedItem("itemFlightRec");
Menu("","MainMenu").setFocusedItem("item_menuDataCom");
Menu("","MainMenu").setFocusedItem("item_menuMaintenance");
MenuSubmenuItem("MainMenu","item_menuMaintenance").pressItem("0");
MenuSubmenuItem("menuMaintenance","item_menuSetup").pressItem("0");
MenuSubmenuItem("menuSetup","item_menuGeneral").pressItem("0");
Menu("menuSetup","menuGeneral").setFocusedItem("itemObstacleWarning");
MenuTextItem("menuGeneral","itemObstacleWarning").pressItem("0");
CheckBox("ObstacleWarningDialog","chkEnable").setChecked("true");
Dialog("","ObstacleWarningDialog").setFocusWidget("rbtManual");
Dialog("","ObstacleWarningDialog").setFocusWidget("rbtAuto");
Dialog("","ObstacleWarningDialog").setFocusWidget("chkInfinityHeight");
Dialog("","ObstacleWarningDialog").setFocusWidget("btnOk");
Button("ObstacleWarningDialog","btnOk").pressButton("0");
